repos:
-   repo: local
    hooks:
    -   id: just-pre-commit
        name: Running 'just pre_commit' command
        entry: just pre_commit
        language: system
        pass_filenames: false
        verbose: true
